#!/usr/bin/env python3
import os

PACKS_DIR  = 'soundpacks'
OUTPUT     = os.path.join('src', 'embedded_packs.c')
MAX_PACKS  = 32
MAX_FILES  = 128

def c_sym(pack_name, filename):
    def encode(s):
        out = []
        for ch in s:
            if ch.isalnum():
                out.append(ch)
            else:
                out.append(f'x{ord(ch):02x}')
        return ''.join(out)
    return 'emb_' + encode(pack_name) + '__' + encode(filename)

def main():
    if not os.path.isdir(PACKS_DIR):
        print(f'[embed] No soundpacks/ dir found - skipping.')
        with open(OUTPUT, 'w') as f:
            f.write('#include "../include/soundpack.h"\n')
            f.write('const EmbeddedPack g_embedded_packs[] = {{0}};\n')
            f.write('const int          g_embedded_pack_count = 0;\n')
        return

    packs = sorted([
        d for d in os.listdir(PACKS_DIR)
        if os.path.isdir(os.path.join(PACKS_DIR, d))
        and os.path.isfile(os.path.join(PACKS_DIR, d, 'config.json'))
    ])

    if not packs:
        print('[embed] No packs found in soundpacks/ - writing empty registry.')
        with open(OUTPUT, 'w') as f:
            f.write('#include "../include/soundpack.h"\n')
            f.write('const EmbeddedPack g_embedded_packs[] = {{0}};\n')
            f.write('const int          g_embedded_pack_count = 0;\n')
        return

    lines = []
    lines.append('/* AUTO-GENERATED by tools/embed_packs.py - DO NOT EDIT */')
    lines.append('#include "../include/soundpack.h"')
    lines.append('')

    pack_structs = []

    for pack_dir in packs:
        pack_path = os.path.join(PACKS_DIR, pack_dir)
        files = sorted(os.listdir(pack_path))

        file_structs = []

        for fname in files:
            fpath = os.path.join(pack_path, fname)
            if not os.path.isfile(fpath):
                continue

            sym = c_sym(pack_dir, fname)
            data = open(fpath, 'rb').read()
            size = len(data)

            lines.append(f'/* {pack_dir}/{fname} ({size} bytes) */')
            lines.append(f'static const unsigned char {sym}[] = {{')

            row = []
            for _, byte in enumerate(data):
                row.append(f'0x{byte:02x}')
                if len(row) == 16:
                    lines.append('    ' + ','.join(row) + ',')
                    row = []
            if row:
                lines.append('    ' + ','.join(row))
            lines.append('};')
            lines.append(f'static const unsigned int {sym}_size = {size};')
            lines.append('')

            safe_fname = fname.replace('\\', '\\\\').replace('"', '\\"')
            file_structs.append(
                f'    {{ "{safe_fname}", {sym}, {sym}_size }}'
            )

        if not file_structs:
            continue

        arr_sym = c_sym(pack_dir, 'files')
        lines.append(f'static const EmbeddedFile {arr_sym}[] = {{')
        lines.append(',\n'.join(file_structs))
        lines.append('};')
        lines.append('')

        pack_structs.append(
            f'    {{ "{pack_dir}", {arr_sym}, '
            f'{len(file_structs)} }}'
        )

    lines.append('const EmbeddedPack g_embedded_packs[] = {')
    lines.append(',\n'.join(pack_structs) if pack_structs else '    {0}')
    lines.append('};')
    lines.append(f'const int g_embedded_pack_count = {len(pack_structs)};')
    lines.append('')

    with open(OUTPUT, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')

    total = sum(
        os.path.getsize(os.path.join(PACKS_DIR, p, fn))
        for p in packs
        for fn in os.listdir(os.path.join(PACKS_DIR, p))
        if os.path.isfile(os.path.join(PACKS_DIR, p, fn))
    )
    print(f'[embed] {len(packs)} pack(s) embedded - '
          f'{total / 1024:.1f} KB total -> {OUTPUT}')

if __name__ == '__main__':
    main()